name: Wake up the bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 9-23,0-3 * * *'

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://gogogadgetto.herokuapp.com